# ansible-playbook -i "localhost," -c local split.yml
---
- hosts: localhost
  tasks:
    - name: test source profile
      shell: source /etc/bashrc
      register: output
      args:
        executable: /bin/bash

    - debug: msg="{{ output }}"
